apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: vault-gateway
  namespace: vault
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "vault.local"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault-virtualservice
  namespace: vault
spec:
  hosts:
  - "vault.local"
  gateways:
  - vault-gateway
  http:
  - route:
    - destination:
        host: vault.vault.svc.cluster.local
        port:
          number: 8200
