apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nombre de tu aplicación en Argo CD
  name: istio-base
  namespace: argocd
spec:
  # El proyecto de Argo CD al que pertenece esta aplicación
  project: default
  
  source:
    # URL del repositorio de charts de Istio
    repoURL: https://istio-release.storage.googleapis.com/charts
    # Nombre del chart que vamos a instalar (el "base" para los CRDs)
    chart: base
    # La versión del chart de Istio. 
    # Asegúrate de usar la versión más reciente y estable.
    targetRevision: "1.22.0"
  
  destination:
    # La URL del clúster de Kubernetes, por defecto.
    server: https://kubernetes.default.svc
    # El namespace donde se instalará Istio.
    namespace: istio-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Esta opción es crucial: Argo CD creará el namespace si no existe.
      - CreateNamespace=true