apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-gateway
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway 
    targetRevision: "1.22.0"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true