apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-v2
  namespace: hola-mundo-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo-v2
  template:
    metadata:
      labels:
        app: hola-mundo-v2
    spec:
      containers:
        - name: hola-mundo-v2
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: hola-mundo-v2-html
