apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-hola-mundo-v2
  namespace: hola-mundo-v2
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    roleName: "my-role-hola-mundo-v2"
    objects: |
      - objectName: "secret/data/hola-mundo-v2/config"
        secretPath: "secret/data/hola-mundo-v2/config"