apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo
      version: v1
  template:
    metadata:
      labels:
        app: hola-mundo
        version: v1
    spec:
      containers:
      - name: hola-mundo
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: hola-mundo-html-v1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hola-mundo-html-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hola Mundo v1</h1>
    </body>
    </html>