# Este manifiesto crea una nueva aplicación en Argo CD para desplegar
# tu servicio "hola-mundo-v2" usando los manifiestos que creaste.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nombre de la aplicación en Argo CD
  name: hola-mundo-v2-app
  namespace: argocd
spec:
  # El proyecto de Argo CD al que pertenece esta aplicación
  project: default
  
  source:
    # URL del repositorio Git donde se encuentran los manifiestos de la app
    repoURL: https://github.com/fpultera/lab-istio.git
    targetRevision: HEAD
    # La ruta dentro del repositorio donde están los archivos YAML de la app
    # Se asume que el manifiesto para v2 está en una ruta diferente.
    path: guestbook/chart/hola-mundo-v2
    
  destination:
    # La URL del clúster de Kubernetes, por defecto
    server: https://kubernetes.default.svc
    # El namespace donde se desplegarán los recursos de la v2.
    # Es una buena práctica separar las versiones en namespaces diferentes.
    namespace: hola-mundo-v2
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Esta opción es crucial: Argo CD creará el namespace si no existe.
      - CreateNamespace=true