# Este manifiesto crea una nueva aplicación en Argo CD para desplegar
# tu servicio "hola-mundo-v1" usando los manifiestos que creaste.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nombre de la aplicación en Argo CD
  name: hola-mundo-v1-app
  namespace: argocd
spec:
  # El proyecto de Argo CD al que pertenece esta aplicación
  project: default
  
  source:
    # URL del repositorio Git donde se encuentran los manifiestos de la app
    repoURL: git@github.com-personal:fpultera/lab-istio.git
    targetRevision: HEAD
    # La ruta dentro del repositorio donde están los archivos YAML de la app
    path: guestbook/chart
    
  destination:
    # La URL del clúster de Kubernetes, por defecto
    server: https://kubernetes.default.svc
    # El namespace donde se desplegarán los recursos.
    # En este caso, el namespace será creado por la aplicación misma.
    namespace: hola-mundo-v1
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Esta opción es crucial: Argo CD creará el namespace si no existe.
      - CreateNamespace=true
