# Este manifiesto crea una nueva aplicación en Argo CD para gestionar
# el VirtualService que divide el tráfico entre las versiones v1 y v2.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nombre de la aplicación en Argo CD
  name: hola-mundo-splitter-app
  namespace: argocd
spec:
  # El proyecto de Argo CD al que pertenece esta aplicación
  project: default
  
  source:
    # URL del repositorio Git donde se encuentra el manifiesto
    # del VirtualService.
    repoURL: https://github.com/fpultera/lab-istio.git
    targetRevision: HEAD
    # La ruta dentro del repositorio donde se encuentra el VirtualService.
    # Debes asegurarte de colocar el archivo YAML en esta ruta.
    path: guestbook/chart/gateway/hola-mundo-vs.yaml
    
  destination:
    # El clúster de Kubernetes donde se desplegará el VirtualService
    server: https://kubernetes.default.svc
    # El namespace de destino para el VirtualService.
    # En este caso, el manifiesto se aplicará en el namespace 'default'.
    namespace: default
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true