apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fpultera/lab-istio.git
    targetRevision: main
    path: manifests/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
